import { lookupArchive } from '@subsquid/archive-registry'
import dotenv from 'dotenv'
dotenv.config()

export const CHAIN_NODE: string = process.env.ASTAR_CHAIN_NODE!
export const SUBSQUID_ARCHIVE = lookupArchive('astar', { release: 'FireSquid' })

export const FACTORY_ADDRESS = '0xA9473608514457b4bF083f9045fA63ae5810A03E'.toLowerCase()
export const FACTORY_CREATION_BLOCK = 219508
export const STABLESWAP_POOLS: [string, number][] = []
// Generated by pairsProcessor.ts, consumed by processor.ts
export const POOLS_JSON_FILE = './assets/pools_arthswap.json'

export const WRAPPED_NATIVE_ADDRESS = '0xAeaaf0e2c81Af264101B9129C00F4440cCF0F720'.toLowerCase() // WASTR
export const WRAPPED_NATIVE_USDC_ADDRESS = '0xBB1290c1829007F440C771b37718FAbf309cd527'.toLowerCase() // WASTR_ceUSDC
export const USDC = '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98'.toLowerCase() // ceUSDC
export const DOT = '0xffffffffffffffffffffffffffffffffffffffff'.toLowerCase()
export const WHITELIST: string[] = [
    WRAPPED_NATIVE_ADDRESS,
    USDC,
]
