import { lookupArchive } from '@subsquid/archive-registry'
import dotenv from 'dotenv'
dotenv.config()

export const CHAIN_NODE: string = process.env.MOONBEAM_CHAIN_NODE!
export const SUBSQUID_ARCHIVE = lookupArchive('moonbeam', { release: 'FireSquid' })

export const FACTORY_ADDRESS = '0x68A384D826D3678f78BB9FB1533c7E9577dACc0E'.toLowerCase()
export const FACTORY_CREATION_BLOCK = 173814
export const STABLESWAP_POOLS: [string, number][] = [
    ['0xb1bc9f56103175193519ae1540a0a4572b1566f6', 2119230], // USDC.wh/USDt.xc/BUSD.wh/FRAX
    // Below is a 'MetaPool' where one side is the LP token for the above wormhole 4Pool 
    ['0xa1ffdc79f998e7fa91ba3a6f098b84c9275b0483', 2317884], // USDC.axl/Base4Pool_wh_LP
    ['0x422b5b7a15fb12c518aa29f9def640b4773427f8', 1202049], // USDC.mad/USDT.mad/DAI.mad/FRAX
    ['0x7fbe3126c03444d43fc403626ec81e3e809e6b46', 1282934], // Stella4Pool/MAI - another MetaPool
]
// Generated by pairsProcessor.ts, consumed by processor.ts
export const POOLS_JSON_FILE = './assets/pools_stellaswap.json'

export const WRAPPED_NATIVE_ADDRESS = '0xAcc15dC74880C9944775448304B263D191c6077F'.toLowerCase() // WGLMR
export const WRAPPED_NATIVE_USDC_ADDRESS = '0x8ccbbcaf58f5422f6efd4034d8e8a3c9120adf79'.toLowerCase() // WGLMR_USDC.wh
export const USDC = '0x931715fee2d06333043d11f658c8ce934ac61d0c'.toLowerCase() // USDC.wh
export const DOT = '0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080'.toLowerCase() // xcDOT
export const WHITELIST: string[] = [
    WRAPPED_NATIVE_ADDRESS,
    USDC,
]
